### ISSUE TITLE
Error when running XOM blueprint

### ISSUE THREAD

**Issue by balk77** [PimDoos/ha-sessy-examples#16]
Hi, I just started running the XOM blueprint and got this error:
```
Error: ValueError: Template error: int got invalid input 'unknown' when rendering template '{% set num_optimal = ((setpoint | abs) / optimal_max_power) | round(0,'ceil') %} {% set batteries = namespace(entities=[], available=[], standby=[]) %} {% for i in range(0,battery_count) %} {% if batteries.available | count < num_optimal and states(battery_strategy_entity[i]) == "api" and states(battery_state_entity[i]) != "error" and (states(battery_soc_entity[i]) | int >= min_battery_level or setpoint < 0) and (states(battery_state_entity[i]) != "battery_empty" or setpoint < 0) and (states(battery_soc_entity[i]) | int <= max_battery_level or setpoint > 0) and (states(battery_state_entity[i]) != "battery_full" or setpoint > 0) %} {% set batteries.available = batteries.available + [i] %} {% else %} {% set batteries.standby = batteries.standby + [i] %} {% endif %} {% endfor %} {% for i in batteries.available %} {% set value = (setpoint / (batteries.available | count)) | int %} {% set value = [[value,-2200] | max, 2200] | min %} {% set batteries.entities = batteries.entities + [{"setpoint":battery_setpoint_entity[i], "strategy": battery_strategy_entity[i], "value":value}] %} {% endfor %} {% for i in batteries.standby %} {% set batteries.entities = batteries.entities + [{"setpoint":battery_setpoint_entity[i], "strategy": battery_strategy_entity[i], "value":0}] %} {% endfor %} {{ batteries.entities }}' but no default was specified

```
My input vars:
```
alias: Sessy XOM - no discharge
description: ''
use_blueprint:
  path: PimDoos/sessy-xom.yaml
  input:
    grid_entity: sensor.dsmr_reading_electricity_currently_net_consumption
    battery_device:
      - 27a1d72a74c7dd196d43be3073a5b473
      - f2618adde7c515f02dcbc861158f3163
    setpoint_smoothing_value: 200
    battery_soc_min: 10
    battery_soc_max: 95
    setpoint_max: 0
    update_timeout:
      hours: 0
      minutes: 0
      seconds: 5
    update_interval:
      hours: 0
      minutes: 0
      seconds: 30
```
where `sensor.dsmr_reading_electricity_currently_net_consumption` is the difference between power in and power out in kW which was a small float (-0.229  at the time of error).
I have now change that to W and made it an int. I will report what the result is.
edit: same issue when using an int
